// This file is automatically generated. Do not edit it directly.
import { api, auth } from "@/integrations/api/client";

// Mock supabase object for compatibility
export const supabase = {
  auth,
  from: (table: string) => ({
    select: (columns = '*') => ({
      eq: (column: string, value: any) => ({
        order: (orderColumn: string) => ({
          execute: () => api.from(table).eq(column, value).order(orderColumn).execute()
        }),
        single: () => api.from(table).eq(column, value).single().execute(),
        execute: () => api.from(table).eq(column, value).execute()
      }),
      order: (orderColumn: string) => ({
        execute: () => api.from(table).order(orderColumn).execute()
      }),
      single: () => api.from(table).single().execute(),
      execute: () => api.from(table).select(columns).execute()
    }),
    insert: (data: any) => api.from(table).insert(data),
    update: (data: any) => api.from(table).update(data),
    delete: () => ({
      eq: (column: string, value: any) => api.from(table).eq(column, value).delete(value)
    })
  })
};